### ISSUE TITLE
Présentation de votre sujet

### ISSUE THREAD

**Issue by benel** [UTT-GL03/EcoMeteo#1]
Merci pour la partie introductive de votre travail (choix du sujet, utilité sociale, impact de la numérisation). C'est plutôt réussi.

Attention à la typographie des listes : même présentée sous forme de liste, une phrase reste une phrase. En particulier : 
- le dernier item doit se terminer par un point,
- les autres par une virgule (ou parfois un point-virgule),
- les items ne doivent pas commencer par une majuscule.

Sur la nécessité de cacher l'heure de lever et du coucher du soleil, il me semble que votre argument avait laissé vos collègues un peu dubitatifs. Outre le faible impact environemental et cognitif de la chose, je pense que ça permet de contextualiser la prévision horaire. En effet, on ne peut pas dire que le temps est ensoleillé si on est en pleine nuit... Après c'est vous qui voyez. Mais ce serait dommage d'attirer vos interlocuteurs à débattre d'un sujet qui n'est peut-être pas central.

Concernant le rafraîchissement automatique, vous pouvez aussi choisir de ne pas en faire du tout. Après tout, il y a un bouton pour ça si les personnes le souhaitent. Là aussi c'est vous qui voyez, mais explicitez le choix de conception quel que soit celui que vous choisirez.

Concernant le modèle de prévision, il faudrait expliciter que ce n'est pas le fait que vous ne demandiez pas qui va empêcher les météorologues de les calculer. Par contre,  à terme, effectivement s'il y a une disparition massive de cette attente de la société, ça pourrait faire une différence...

Merci d'avance.

**Comment by Asmeeeee** [comment]
done
